spring.application.name: tapsnap-game-server
#logging.level.io.rsocket: DEBUG
#debug: true
management:
  endpoints:
    web:
      exposure:
        include:
          - app
          - health
          - info
          - prometheus
          - metrics

server:
  port: 8008
spring:
  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /