spring.application.name: meetup-game-server
logging.level.io.rsocket: DEBUG
management.endpoints.web.exposure.include: "*"
debug: true

server:
  port: 8008
spring:
  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /